name: Callable — Update Actions Versions

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        default: '20'
      pr-team:
        type: string
        default: ''
    secrets:
      GH_TOKEN:
        required: true

jobs:
  update-actions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@mri-qbox-brasil'

      - name: Install workflows
        run: npm install --no-save @mri-qbox-brasil/workflows
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Run update
        run: npx workflows update-actions
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          PR_TEAM: ${{ inputs.pr-team }}
