name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install --prefer-offline --no-audit --no-fund --prefix .release

      - name: Build
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)
          bash scripts/build.sh $REPO_NAME

      - name: Release
        run: .release/node_modules/.bin/semantic-release --config .release/release.config.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}