name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          scope: '@mri-qbox-brasil'

      - name: Install deps
        run: npm install --prefer-offline --no-audit --no-fund --prefix .release

      - name: Release
        run: .release/node_modules/.bin/semantic-release --extends ./.release/release.config.cjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_PATH: ${{ github.workspace }}/.release/node_modules
